disabling functional in github workflow. datetime version fix

diff --git a/.github/workflows/run-regression.yml b/.github/workflows/run-regression.yml
--- a/.github/workflows/run-regression.yml
+++ b/.github/workflows/run-regression.yml
@@ -356,33 +356,33 @@ jobs:
           name: ${{ env.SUITE }}-artifacts
           path: ${{ env.artifact_paths}}
 
-  functional:
-    runs-on: self-hosted
-    env:
-      SUITE: clickhouse/functional
-    if: ${{ inputs.suite == 'all' || inputs.suite == 'functional' }}
-    steps:
-      - uses: actions/checkout@v3
+  # functional:
+  #   runs-on: self-hosted
+  #   env:
+  #     SUITE: clickhouse/functional
+  #   if: ${{ inputs.suite == 'all' || inputs.suite == 'functional' }}
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Setup
-        run: .github/setup.sh
+  #     - name: Setup
+  #       run: .github/setup.sh
 
-      - name: Run ${{ env.SUITE }} suite
-        run: python3
-              -u ${{ env.SUITE }}/functional.py
-              --clickhouse-binary-path ${{ env.clickhouse_binary_path }}  
-              --clickhouse-version ${{ env.version }} 
-              ${{ env.args }}
+  #     - name: Run ${{ env.SUITE }} suite
+  #       run: python3
+  #             -u ${{ env.SUITE }}/functional.py
+  #             --clickhouse-binary-path ${{ env.clickhouse_binary_path }}  
+  #             --clickhouse-version ${{ env.version }} 
+  #             ${{ env.args }}
 
-      - name: Create and upload logs
-        if: success() || failure()
-        run: .github/create_and_upload_logs.sh ${{ vars.UPLOAD_LOGS }}
+  #     - name: Create and upload logs
+  #       if: success() || failure()
+  #       run: .github/create_and_upload_logs.sh ${{ vars.UPLOAD_LOGS }}
 
-      - uses: actions/upload-artifact@v3
-        if: always()
-        with:
-          name: clickhouse-functional-artifacts
-          path: ${{ env.artifact_paths}}
+  #     - uses: actions/upload-artifact@v3
+  #       if: always()
+  #       with:
+  #         name: clickhouse-functional-artifacts
+  #         path: ${{ env.artifact_paths}}
 
   kafka:
     runs-on: self-hosted
@@ -523,47 +523,33 @@ jobs:
           name: ldap-role_mapping-artifacts
           path: ${{ env.artifact_paths}}
 
-  # lightweight_delete:
-  #   runs-on: self-hosted
-  #   env:
-  #     SUITE: lightweight_delete
-  #   if: ${{ inputs.suite == 'all' || inputs.suite == 'lightweight_delete' }}
-  #   steps:
-  #     - uses: actions/checkout@v3
+  lightweight_delete:
+    runs-on: self-hosted
+    env:
+      SUITE: lightweight_delete
+    if: ${{ inputs.suite == 'all' || inputs.suite == 'lightweight_delete' }}
+    steps:
+      - uses: actions/checkout@v3
 
-  #     - name: Setup
-  #       run: .github/setup.sh
+      - name: Setup
+        run: .github/setup.sh
 
-  #     - name: Run ${{ env.SUITE }} suite
-  #       run: python3 
-  #             -u ${{ env.SUITE }}/regression.py
-  #             --test-to-end
-  #             --local
-  #             --collect-service-logs 
-  #             --output ${{ vars.OUTPUT }} 
-  #             --parallel ${{ vars.PARALLEL }}
-  #             --clickhouse-binary-path ${{ env.clickhouse_binary_path }}  
-  #             --clickhouse-version ${{ env.version }} 
-  #             --attr project="$GITHUB_REPOSITORY" project.id="$GITHUB_REPOSITORY_ID" user.name="$GITHUB_ACTOR" version="${{ inputs.version }}" package="${{ inputs.package }}" repository="https://github.com/Altinity/clickhouse-regression" commit.hash="$GITHUB_SHA" job.id="$GITHUB_RUN_ID" job.url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" arch="${{ vars.ARCH }}"
-  #             --log raw.log
+      - name: Run ${{ env.SUITE }} suite
+        run: python3 
+              -u ${{ env.SUITE }}/regression.py
+              --clickhouse-binary-path ${{ env.clickhouse_binary_path }}
+              --clickhouse-version ${{ env.version }}
+              ${{ env.args }}
 
-  #     - name: Create and upload logs
-  #       if: success() || failure()
-  #       run: .github/create_and_upload_logs.sh ${{ vars.UPLOAD_LOGS }}
+      - name: Create and upload logs
+        if: success() || failure()
+        run: .github/create_and_upload_logs.sh ${{ vars.UPLOAD_LOGS }}
 
-  #     - uses: actions/upload-artifact@v3
-  #       if: always()
-  #       with:
-  #         name: ${{ env.SUITE }}-artifacts
-  #         path: |
-  #           ./report.html
-  #           ./*.log.txt
-  #           ./*.log
-  #           ./*.html
-  #           ./*/_instances/*/logs/*.log
-  #           ./*/*/_instances/*/logs/*.log
-  #           ./*/_instances/*.log
-  #           ./*/*/_instances/*.log
+      - uses: actions/upload-artifact@v3
+        if: always()
+        with:
+          name: ${{ env.SUITE }}-artifacts
+          path: ${{ env.artifact_paths}}
 
   map_type:
     runs-on: self-hosted
@@ -799,57 +785,43 @@ jobs:
           name: ${{ env.SUITE }}-artifacts
           path: ${{ env.artifact_paths}}
 
-  # benchmark:
-  #   runs-on: self-hosted
-  #   env:
-  #     SUITE: benchmark
-  #   if: ${{ inputs.suite == 'all' || inputs.suite == 'benchmark' }}
-  #   steps:
-  #     - uses: actions/checkout@v3
+  benchmark:
+    runs-on: self-hosted
+    env:
+      SUITE: s3/benchmark
+    if: ${{ inputs.suite == 'all' || inputs.suite == 'benchmark' }}
+    steps:
+      - uses: actions/checkout@v3
 
-  #     - name: Setup
-  #       run: .github/setup.sh
+      - name: Setup
+        run: .github/setup.sh
 
-  #     - name: Run ${{ env.SUITE }} suite
-  #       run: python3 
-  #             -u ${{ env.SUITE }}/benchmark.py
-                # --storage minio
-                # --storage aws_s3
-                # --aws-s3-bucket ${{ secrets.AWS_BUCKET }}
-                # --aws-s3-region ${{ secrets.AWS_REGION }}
-                # --aws-s3-key-id ${{ secrets.AWS_KEY_ID }}
-                # --aws-s3-access-key ${{ secrets.AWS_ACCESS_KEY }}
-                # --storage gcs
-                # --gcs-uri ${{ secrets.GCS_URI }}
-                # --gcs-key-id ${{ secrets.GCS_KEY_ID }}
-                # --gcs-key-secret ${{ secrets.GCS_KEY_SECRET }}
-  #             --test-to-end
-  #             --local
-  #             --collect-service-logs 
-  #             --output ${{ vars.OUTPUT }} 
-  #             --parallel ${{ vars.PARALLEL }}
-  #             --clickhouse-binary-path ${{ env.clickhouse_binary_path }}  
-  #             --clickhouse-version ${{ env.version }} 
-  #             --attr project="$GITHUB_REPOSITORY" project.id="$GITHUB_REPOSITORY_ID" user.name="$GITHUB_ACTOR" version="${{ inputs.version }}" package="${{ inputs.package }}" repository="https://github.com/Altinity/clickhouse-regression" commit.hash="$GITHUB_SHA" job.id="$GITHUB_RUN_ID" job.url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" arch="${{ vars.ARCH }}"
-  #             --log raw.log
+      - name: Run ${{ env.SUITE }} suite
+        run: python3 
+              -u ${{ env.SUITE }}/benchmark.py
+              --storage minio
+              --storage aws_s3
+              --aws-s3-bucket ${{ secrets.AWS_BUCKET }}
+              --aws-s3-region ${{ secrets.AWS_REGION }}
+              --aws-s3-key-id ${{ secrets.AWS_KEY_ID }}
+              --aws-s3-access-key ${{ secrets.AWS_ACCESS_KEY }}
+              --storage gcs
+              --gcs-uri ${{ secrets.GCS_URI }}
+              --gcs-key-id ${{ secrets.GCS_KEY_ID }}
+              --gcs-key-secret ${{ secrets.GCS_KEY_SECRET }}
+              --clickhouse-binary-path ${{ env.clickhouse_binary_path }}
+              --clickhouse-version ${{ env.version }}
+              ${{ env.args }}
 
-  #     - name: Create and upload logs
-  #       if: success() || failure()
-  #       run: .github/create_and_upload_logs.sh ${{ vars.UPLOAD_LOGS }}
+      - name: Create and upload logs
+        if: success() || failure()
+        run: .github/create_and_upload_logs.sh ${{ vars.UPLOAD_LOGS }}
 
-  #     - uses: actions/upload-artifact@v3
-  #       if: always()
-  #       with:
-  #         name: ${{ env.SUITE }}-artifacts
-  #         path: |
-  #           ./report.html
-  #           ./*.log.txt
-  #           ./*.log
-  #           ./*.html
-  #           ./*/_instances/*/logs/*.log
-  #           ./*/*/_instances/*/logs/*.log
-  #           ./*/_instances/*.log
-  #           ./*/*/_instances/*.log
+      - uses: actions/upload-artifact@v3
+        if: always()
+        with:
+          name: benchmark-artifacts
+          path: ${{ env.artifact_paths}}
 
   ssl_server:
     runs-on: self-hosted
